remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
url: https://fatbob67.github.io/SynthAdvent/
baseurl: /SynthAdvent
title: [Advent Synth]
description: [Building a synth from the Electronic Sound Advent Calendar]